syntax = "proto2";

package apollo.canbus;

message Acu1_151 {
// Control Message
  enum Acu1_steeringcontrolflagType {
    ACU1_STEERINGCONTROLFLAG_NO_REQUEST = 0;
    ACU1_STEERINGCONTROLFLAG_REQUEST = 1;
    ACU1_STEERINGCONTROLFLAG_RESERVED = 2;
  }
  // This signal is steering torque request [Nm] [-20|20]
  optional double acu1_steeringtargettorque = 1;
  // This signal is steering speed request [deg/s] [0|500]
  optional int32 acu1_steeringtargetspeed = 2;
  // This signal is the status of steering control request [] [0|3]
  optional Acu1_steeringcontrolflagType acu1_steeringcontrolflag = 3;
  // This signal is steering angle request [deg] [-600|600]
  optional double acu1_steeringtargetangle = 4;
  // The Livecounter is used to check the signal consistency of the messages [count] [0|15]
  optional int32 acu1_livecounter = 5;
  // The checksum is used to check whether the data transmission errors [check] [0|255]
  optional int32 acu1_checksum = 6;
}

message Acu2_152 {
// Control Message
  enum Acu2_drivingcontrolflagType {
    ACU2_DRIVINGCONTROLFLAG_NO_REQUEST = 0;
    ACU2_DRIVINGCONTROLFLAG_REQUESTTHROTTLE = 1;
    ACU2_DRIVINGCONTROLFLAG_RESERVEDSPEED = 2;
    ACU2_DRIVINGCONTROLFLAG_RESERVED = 3;
  }
  // [km/h] [0|126]
  optional double acu2_drivingtargetspeed = 1;
  // This signal is acceleration pedal position request [Nm] [0|350]
  optional double acu2_drivingtargettorque = 2;
  // This signal is acceleration pedal position request [%] [0|100]
  optional double acu2_drivingtargetthrottle = 3;
  // This signal is the status of the driving control request [] [0|3]
  optional Acu2_drivingcontrolflagType acu2_drivingcontrolflag = 4;
  // This signal is acceleration pedal position request [m/s2] [0|10]
  optional double acu2_drivingtargetacceleration = 5;
  // The Livecounter is used to check the signal consistency of the messages [count] [0|15]
  optional int32 acu2_livecounter = 6;
  // The checksum is used to check whether the data transmission errors [check] [0|255]
  optional int32 acu2_checksum = 7;
}

message Acu3_153 {
// Control Message
  enum Acu3_epbcontrolflagType {
    ACU3_EPBCONTROLFLAG_NO_REQUEST = 0;
    ACU3_EPBCONTROLFLAG_RELEASE = 1;
    ACU3_EPBCONTROLFLAG_LOCK = 2;
    ACU3_EPBCONTROLFLAG_RESERVED = 3;
  }
  enum Acu3_geartargetType {
    ACU3_GEARTARGET_P = 0;
    ACU3_GEARTARGET_R = 1;
    ACU3_GEARTARGET_N = 2;
    ACU3_GEARTARGET_D = 3;
    ACU3_GEARTARGET_RESERVED = 4;
  }
  enum Acu3_gearcontrolflagType {
    ACU3_GEARCONTROLFLAG_NO_REQUEST = 0;
    ACU3_GEARCONTROLFLAG_REQUEST = 1;
  }
  enum Acu3_brakingcontrolflagType {
    ACU3_BRAKINGCONTROLFLAG_NO_REQUEST = 0;
    ACU3_BRAKINGCONTROLFLAG_REQUEST_PRESURE = 1;
    ACU3_BRAKINGCONTROLFLAG_REQUEST_DEC = 2;
    ACU3_BRAKINGCONTROLFLAG_REQUEST_POSITION = 3;
  }
  // [%] [0|100]
  optional double acu3_brakingtargetposition = 1;
  // This signal is the status of the braking control request [] [0|3]
  optional Acu3_epbcontrolflagType acu3_epbcontrolflag = 2;
  // This signal is gear request [] [0|7]
  optional Acu3_geartargetType acu3_geartarget = 3;
  // This signal is the status of the gear control request [] [0|1]
  optional Acu3_gearcontrolflagType acu3_gearcontrolflag = 4;
  // This signal is deceleration request for wheel brake [Mpa] [0|10]
  optional double acu3_brakingtargetpressure = 5;
  // This signal is deceleration request for wheel brake [m/s2] [-10|0]
  optional double acu3_brakingtargetdeceleration = 6;
  // This signal is the status of the braking control request [] [0|3]
  optional Acu3_brakingcontrolflagType acu3_brakingcontrolflag = 7;
  // The Livecounter is used to check the signal consistency of the messages [count] [0|15]
  optional int32 acu3_livecounter = 8;
  // The checksum is used to check whether the data transmission errors [check] [0|255]
  optional int32 acu3_checksum = 9;
}

message Acu4_154 {
// Control Message
  enum Acu4_steeringlamprequestType {
    ACU4_STEERINGLAMPREQUEST_OFF = 0;
    ACU4_STEERINGLAMPREQUEST_LEFT_ON = 1;
    ACU4_STEERINGLAMPREQUEST_RIGHT_ON = 2;
    ACU4_STEERINGLAMPREQUEST_RESERVED = 3;
  }
  enum Acu4_hazardlamprequestType {
    ACU4_HAZARDLAMPREQUEST_OFF = 0;
    ACU4_HAZARDLAMPREQUEST_ON = 1;
  }
  // 1power on 3power off [] [0|3]
  optional int32 acu4_powerrequest = 1;
  // 1fall  2 rise 3 stop [] [0|0]
  optional int32 acu4_rrwindow_request = 2;
  // 1fall  2 rise 3 stop [] [0|0]
  optional int32 acu4_rlwindow_request = 3;
  // 1lock 2unlock [] [0|0]
  optional int32 acu4_lock_request = 4;
  // 1fall  2 rise 3 stop [] [0|0]
  optional int32 acu4_frwindow_request = 5;
  // 1fall  2 rise 3 stop [] [0|0]
  optional int32 acu4_flwindow_request = 6;
  // 1on 2 off 3stop [] [0|0]
  optional int32 acu4_boot_request = 7;
  // [] [0|3]
  optional int32 acu4_rearwiperrequest = 8;
  // [] [0|1]
  optional bool acu4_led4request = 9;
  // [] [0|1]
  optional bool acu4_led3request = 10;
  // [] [0|1]
  optional bool acu4_led2request = 11;
  // [] [0|1]
  optional bool acu4_led1request = 12;
  // This signal is the the horn lamp or request [] [0|1]
  optional bool acu4_lamphorn = 13;
  // 0off  1:on [] [0|3]
  optional int32 acu4_whistlerequest = 14;
  // 0stop 1inject water 2slow 3fast [] [0|3]
  optional int32 acu4_frontwiperrequest = 15;
  // 0:OFF 1:LOW 2£ºHIGH [] [0|3]
  optional int32 acu4_beamlamprequest = 16;
  // The Livecounter is used to check the signal consistency of the messages [count] [0|15]
  optional int32 acu4_livecounter = 17;
  // The checksum is used to check whether the data transmission errors [check] [0|255]
  optional int32 acu4_checksum = 18;
  // This signal is steering light request [] [0|3]
  optional Acu4_steeringlamprequestType acu4_steeringlamprequest = 19;
  // This signal is hazard light request [] [0|1]
  optional Acu4_hazardlamprequestType acu4_hazardlamprequest = 20;
}

message Acs1_20c {
// Report Message
  enum Acs1_drivingstatemachineType {
    ACS1_DRIVINGSTATEMACHINE_IDLE = 0;
    ACS1_DRIVINGSTATEMACHINE_CHECK = 1;
    ACS1_DRIVINGSTATEMACHINE_MANUAL = 2;
    ACS1_DRIVINGSTATEMACHINE_REMOTE = 3;
    ACS1_DRIVINGSTATEMACHINE_IPC = 4;
    ACS1_DRIVINGSTATEMACHINE_INTERVENTION = 5;
    ACS1_DRIVINGSTATEMACHINE_EMERGENCY = 6;
    ACS1_DRIVINGSTATEMACHINE_ERROR = 7;
  }
  enum Acs1_geartakeoverstType {
    ACS1_GEARTAKEOVERST_INACTIVE = 0;
    ACS1_GEARTAKEOVERST_TEMP_ACTIVE = 1;
    ACS1_GEARTAKEOVERST_ACTIVE = 2;
    ACS1_GEARTAKEOVERST_RESERVED = 3;
  }
  enum Acs1_gearfailurestType {
    ACS1_GEARFAILUREST_NO_FAIL = 0;
    ACS1_GEARFAILUREST_EGSM_FAIL = 1;
    ACS1_GEARFAILUREST_HCU_FAIL = 2;
    ACS1_GEARFAILUREST_RESERVED = 3;
  }
  enum Acs1_gearautocontrolstType {
    ACS1_GEARAUTOCONTROLST_INACTIVE = 0;
    ACS1_GEARAUTOCONTROLST_ACTIVE = 1;
    ACS1_GEARAUTOCONTROLST_RESERVED = 2;
  }
  enum Acs1_steeringtakeoverstType {
    ACS1_STEERINGTAKEOVERST_INACTIVE = 0;
    ACS1_STEERINGTAKEOVERST_TEMP_ACTIVE = 1;
    ACS1_STEERINGTAKEOVERST_ACTIVE = 2;
    ACS1_STEERINGTAKEOVERST_RESERVED = 3;
  }
  enum Acs1_steeringfailurestType {
    ACS1_STEERINGFAILUREST_NO_FAIL = 0;
    ACS1_STEERINGFAILUREST_EPS_FAIL = 1;
    ACS1_STEERINGFAILUREST_SAS_FAIL = 2;
    ACS1_STEERINGFAILUREST_APA_FAIL = 3;
  }
  enum Acs1_steeringautocontrolstType {
    ACS1_STEERINGAUTOCONTROLST_INACTIVE = 0;
    ACS1_STEERINGAUTOCONTROLST_ACTIVE = 1;
    ACS1_STEERINGAUTOCONTROLST_RESERVED = 2;
  }
  enum Acs1_drivingtakeoverstType {
    ACS1_DRIVINGTAKEOVERST_INACTIVE = 0;
    ACS1_DRIVINGTAKEOVERST_TEMP_ACTIVE = 1;
    ACS1_DRIVINGTAKEOVERST_ACTIVE = 2;
    ACS1_DRIVINGTAKEOVERST_RESERVED = 3;
  }
  enum Acs1_drivingfailurestType {
    ACS1_DRIVINGFAILUREST_NO_FAIL = 0;
    ACS1_DRIVINGFAILUREST_HCU_FAIL = 1;
    ACS1_DRIVINGFAILUREST_RESERVED = 2;
  }
  enum Acs1_drivingautocontrolstType {
    ACS1_DRIVINGAUTOCONTROLST_INACTIVE = 0;
    ACS1_DRIVINGAUTOCONTROLST_ACTIVE = 1;
    ACS1_DRIVINGAUTOCONTROLST_RESERVED = 2;
  }
  enum Acs1_brakingtakeoverstType {
    ACS1_BRAKINGTAKEOVERST_INACTIVE = 0;
    ACS1_BRAKINGTAKEOVERST_TEMP_ACTIVE = 1;
    ACS1_BRAKINGTAKEOVERST_ACTIVE = 2;
    ACS1_BRAKINGTAKEOVERST_RESERVED = 3;
  }
  enum Acs1_brakingfailurestType {
    ACS1_BRAKINGFAILUREST_NO_FAIL = 0;
    ACS1_BRAKINGFAILUREST_ESP_FAIL = 1;
    ACS1_BRAKINGFAILUREST_SS_FAIL = 2;
    ACS1_BRAKINGFAILUREST_HCU_FAIL = 3;
  }
  enum Acs1_brakingautocontrolstType {
    ACS1_BRAKINGAUTOCONTROLST_INACTIVE = 0;
    ACS1_BRAKINGAUTOCONTROLST_ACTIVE = 1;
    ACS1_BRAKINGAUTOCONTROLST_RESERVED = 2;
  }
  // [] [0|3]
  optional int32 acs1_workmode = 1;
  // This signal indicates the state machine of steering. [value] [0|15]
  optional int32 acs1_steeringstatemachine = 2;
  // This signal indicates the state machine of gear. [value] [0|15]
  optional int32 acs1_gearstatemachine = 3;
  // This signal indicates the state machine of driving. [value] [0|15]
  optional Acs1_drivingstatemachineType acs1_drivingstatemachine = 4;
  // This signal indicates the state machine of braking. [value] [0|15]
  optional int32 acs1_brakingstatemachine = 5;
  // This signal indicates the gear is under maunal taking over. [] [0|3]
  optional Acs1_geartakeoverstType acs1_geartakeoverst = 6;
  // This signal indicates the gear is in fault status [] [0|3]
  optional Acs1_gearfailurestType acs1_gearfailurest = 7;
  // This signal indicates the gear is under automatical control or not. [] [0|3]
  optional Acs1_gearautocontrolstType acs1_gearautocontrolst = 8;
  // This signal indicates the steering is under maunal taking over. [] [0|3]
  optional Acs1_steeringtakeoverstType acs1_steeringtakeoverst = 9;
  // This signal indicates the steering is in fault status [] [0|3]
  optional Acs1_steeringfailurestType acs1_steeringfailurest = 10;
  // This signal indicates the steering is under automatical control or not. [] [0|3]
  optional Acs1_steeringautocontrolstType acs1_steeringautocontrolst = 11;
  // The Livecounter is used to check the signal consistency of the messages [count] [0|15]
  optional int32 acs1_livecounter = 12;
  // This signal indicates the driving is under maunal taking over. [] [0|3]
  optional Acs1_drivingtakeoverstType acs1_drivingtakeoverst = 13;
  // This signal indicates the driving is in fault status [] [0|3]
  optional Acs1_drivingfailurestType acs1_drivingfailurest = 14;
  // This signal indicates the driving is under automatical control or not. [] [0|3]
  optional Acs1_drivingautocontrolstType acs1_drivingautocontrolst = 15;
  // The checksum is used to check whether the data transmission errors [check] [0|255]
  optional int32 acs1_checksum = 16;
  // This signal indicates the braking is under maunal taking over. [] [0|3]
  optional Acs1_brakingtakeoverstType acs1_brakingtakeoverst = 17;
  // This signal indicates the braking is in fault status [] [0|3]
  optional Acs1_brakingfailurestType acs1_brakingfailurest = 18;
  // This signal indicates the braking is under automatical control or not. [] [0|3]
  optional Acs1_brakingautocontrolstType acs1_brakingautocontrolst = 19;
}

message Acs2_20d {
// Report Message
  enum Acs2_validitycan7Type {
    ACS2_VALIDITYCAN7_ACTIVE = 0;
    ACS2_VALIDITYCAN7_DEACTIVE = 1;
  }
  enum Acs2_validitycan6Type {
    ACS2_VALIDITYCAN6_ACTIVE = 0;
    ACS2_VALIDITYCAN6_DEACTIVE = 1;
  }
  enum Acs2_validitycan5Type {
    ACS2_VALIDITYCAN5_ACTIVE = 0;
    ACS2_VALIDITYCAN5_DEACTIVE = 1;
  }
  enum Acs2_validitycan4Type {
    ACS2_VALIDITYCAN4_ACTIVE = 0;
    ACS2_VALIDITYCAN4_DEACTIVE = 1;
  }
  enum Acs2_validitycan3Type {
    ACS2_VALIDITYCAN3_ACTIVE = 0;
    ACS2_VALIDITYCAN3_DEACTIVE = 1;
  }
  enum Acs2_validitycan2Type {
    ACS2_VALIDITYCAN2_ACTIVE = 0;
    ACS2_VALIDITYCAN2_DEACTIVE = 1;
  }
  enum Acs2_validitycan1Type {
    ACS2_VALIDITYCAN1_ACTIVE = 0;
    ACS2_VALIDITYCAN1_DEACTIVE = 1;
  }
  enum Acs2_validitycan0Type {
    ACS2_VALIDITYCAN0_ACTIVE = 0;
    ACS2_VALIDITYCAN0_DEACTIVE = 1;
  }
  enum Acs2_buttonjerkType {
    ACS2_BUTTONJERK_NO_PRESS = 0;
    ACS2_BUTTONJERK_PRESS = 1;
  }
  enum Acs2_button3Type {
    ACS2_BUTTON3_NO_PRESS = 0;
    ACS2_BUTTON3_PRESS = 1;
  }
  enum Acs2_button2Type {
    ACS2_BUTTON2_NO_PRESS = 0;
    ACS2_BUTTON2_PRESS = 1;
  }
  enum Acs2_button1Type {
    ACS2_BUTTON1_NO_PRESS = 0;
    ACS2_BUTTON1_PRESS = 1;
  }
  // This signal indicates the validity of CAN5 [] [0|1]
  optional Acs2_validitycan7Type acs2_validitycan7 = 1;
  // This signal indicates the validity of CAN4 [] [0|1]
  optional Acs2_validitycan6Type acs2_validitycan6 = 2;
  // This signal indicates the validity of CAN5 [] [0|1]
  optional Acs2_validitycan5Type acs2_validitycan5 = 3;
  // This signal indicates the validity of CAN4 [] [0|1]
  optional Acs2_validitycan4Type acs2_validitycan4 = 4;
  // This signal indicates the validity of CAN3 [] [0|1]
  optional Acs2_validitycan3Type acs2_validitycan3 = 5;
  // This signal indicates the validity of CAN2 [] [0|1]
  optional Acs2_validitycan2Type acs2_validitycan2 = 6;
  // This signal indicates the validity of CAN1 [] [0|1]
  optional Acs2_validitycan1Type acs2_validitycan1 = 7;
  // This signal indicates the validity of CAN0 [] [0|1]
  optional Acs2_validitycan0Type acs2_validitycan0 = 8;
  // This signal indicates the version of software [version] [0|655.35]
  optional double acs2_version = 9;
  // The Livecounter is used to check the signal consistency of the messages [count] [0|15]
  optional int32 acs2_livecounter = 10;
  // This signal indicates the state of Jerk Button [] [0|1]
  optional Acs2_buttonjerkType acs2_buttonjerk = 11;
  // The checksum is used to check whether the data transmission errors [check] [0|255]
  optional int32 acs2_checksum = 12;
  // This signal indicates the state of Button2 [] [0|1]
  optional Acs2_button3Type acs2_button3 = 13;
  // This signal indicates the state of Button2 [] [0|1]
  optional Acs2_button2Type acs2_button2 = 14;
  // This signal indicates the state of Button1 [] [0|1]
  optional Acs2_button1Type acs2_button1 = 15;
}

message Acs3_20e {
// Report Message
  // [] [0|255]
  optional int32 acs3_data7 = 1;
  // [] [0|255]
  optional int32 acs3_data6 = 2;
  // [] [0|255]
  optional int32 acs3_data5 = 3;
  // [] [0|255]
  optional int32 acs3_data4 = 4;
  // [] [0|255]
  optional int32 acs3_data3 = 5;
  // [] [0|255]
  optional int32 acs3_data2 = 6;
  // [] [0|255]
  optional int32 acs3_data1 = 7;
  // [] [0|255]
  optional int32 acs3_data0 = 8;
}

message Vcu1_210 {
// Report Message
  // The signal indicates the actual applied overlay toque in EPS. [Nm] [-10|10]
  optional double vcu1_overlayinputtorque = 1;
  // The signal indicates the torque measured by the torque sensor at the steering wheel [Nm] [-10|10]
  optional double vcu1_handsteeringtorque = 2;
  // The Livecounter is used to check the signal consistency of the messages [count] [0|15]
  optional int32 vcu1_livecounter = 3;
  // The checksum is used to check whether the data transmission errors [check] [0|255]
  optional int32 vcu1_checksum = 4;
  // This signal indicates the teering wheel rotation speed. anticlockwise=negative, clockwise=positive [deg/s] [-600|600]
  optional double vcu1_steeringspeed = 5;
  // This signal indicates the angle of steering wheel. anticlockwise=negative, clockwise=positive [deg] [-600|600]
  optional double vcu1_steeringangle = 6;
}

message Vcu2_211 {
// Report Message
  enum Vcu2_brakepedalstType {
    VCU2_BRAKEPEDALST_NO_ACTUATED = 0;
    VCU2_BRAKEPEDALST_ACTUATED = 1;
    VCU2_BRAKEPEDALST_RESERVED = 2;
    VCU2_BRAKEPEDALST_ERROR = 3;
  }
  enum Vcu2_drivingdirectionType {
    VCU2_DRIVINGDIRECTION_STOP = 0;
    VCU2_DRIVINGDIRECTION_FORWARD = 1;
    VCU2_DRIVINGDIRECTION_BACKWARD = 2;
    VCU2_DRIVINGDIRECTION_INVALID_VALUE = 3;
  }
  // The signal indicates the actual pressure in the master cylinder. [bar] [0|200]
  optional double vcu2_mastercylinderpressure = 1;
  // This signal indicates the brake pedal status. [] [0|3]
  optional Vcu2_brakepedalstType vcu2_brakepedalst = 2;
  // The signal describes the raw vehicle speed calculated by ABS. [km/h] [0|300]
  optional double vcu2_vehiclespeed = 3;
  // The signal indicates driving direction of the vehicle. [] [0|3]
  optional Vcu2_drivingdirectionType vcu2_drivingdirection = 4;
  // This signal indicates the calculated acceleration pedal position in cruise control mode. [%] [0|100]
  optional double vcu2_calaccelerationpedalpositio = 5;
  // This signal indicates the actual acceleration pedal position [%] [0|100]
  optional double vcu2_accelpedalposition = 6;
  // The Livecounter is used to check the signal consistency of the messages [count] [0|15]
  optional int32 vcu2_livecounter = 7;
  // The checksum is used to check whether the data transmission errors [check] [0|255]
  optional int32 vcu2_checksum = 8;
}

message Vcu3_212 {
// Report Message
  enum Vcu3_mainswitchType {
    VCU3_MAINSWITCH_INACTIVE = 0;
    VCU3_MAINSWITCH_ACTIVE = 1;
  }
  enum Vcu3_increasespeedswitchType {
    VCU3_INCREASESPEEDSWITCH_INACTIVE = 0;
    VCU3_INCREASESPEEDSWITCH_ACTIVE = 1;
  }
  enum Vcu3_increasedistanceswitchType {
    VCU3_INCREASEDISTANCESWITCH_INACTIVE = 0;
    VCU3_INCREASEDISTANCESWITCH_ACTIVE = 1;
  }
  enum Vcu3_decreasespeedswitchType {
    VCU3_DECREASESPEEDSWITCH_INACTIVE = 0;
    VCU3_DECREASESPEEDSWITCH_ACTIVE = 1;
  }
  enum Vcu3_decreasedistanceswitchType {
    VCU3_DECREASEDISTANCESWITCH_INACTIVE = 0;
    VCU3_DECREASEDISTANCESWITCH_ACTIVE = 1;
  }
  enum Vcu3_cancelswitchType {
    VCU3_CANCELSWITCH_INACTIVE = 0;
    VCU3_CANCELSWITCH_ACTIVE = 1;
  }
  enum Vcu3_gearsecuritybuttonType {
    VCU3_GEARSECURITYBUTTON_NO_PRESSED = 0;
    VCU3_GEARSECURITYBUTTON_PRESSED = 1;
  }
  enum Vcu3_gearparkbuttonType {
    VCU3_GEARPARKBUTTON_NO_PRESSED = 0;
    VCU3_GEARPARKBUTTON_PRESSED = 1;
  }
  enum Vcu3_gearleverpositionType {
    VCU3_GEARLEVERPOSITION_POSITION_0 = 0;
    VCU3_GEARLEVERPOSITION_POSITION_ADD1 = 1;
    VCU3_GEARLEVERPOSITION_POSITION_ADD2 = 2;
    VCU3_GEARLEVERPOSITION_POSITION_SUB1 = 3;
    VCU3_GEARLEVERPOSITION_POSITION_SUB2 = 4;
    VCU3_GEARLEVERPOSITION_RESERVED = 5;
    VCU3_GEARLEVERPOSITION_INVALID_VALUE = 6;
  }
  enum Vcu3_epbswitchType {
    VCU3_EPBSWITCH_NO_PRESS = 0;
    VCU3_EPBSWITCH_UP = 1;
    VCU3_EPBSWITCH_DOWN = 2;
    VCU3_EPBSWITCH_RESERVED = 3;
  }
  enum Vcu3_leverinfoType {
    VCU3_LEVERINFO_P = 0;
    VCU3_LEVERINFO_R = 1;
    VCU3_LEVERINFO_N = 2;
    VCU3_LEVERINFO_D = 3;
    VCU3_LEVERINFO_S = 4;
    VCU3_LEVERINFO_M = 5;
    VCU3_LEVERINFO_W = 6;
    VCU3_LEVERINFO_E = 7;
    VCU3_LEVERINFO_B = 8;
    VCU3_LEVERINFO_RESERVED = 9;
    VCU3_LEVERINFO_NO_CONNECTION = 10;
    VCU3_LEVERINFO_INVALID_VALUE = 11;
  }
  enum Vcu3_epbstatusType {
    VCU3_EPBSTATUS_RELEASED = 0;
    VCU3_EPBSTATUS_RELEASING_OR_LOCKING = 1;
    VCU3_EPBSTATUS_LOCKED = 2;
    VCU3_EPBSTATUS_UNKNOW = 3;
  }
  enum Vcu3_actualgearType {
    VCU3_ACTUALGEAR_P = 0;
    VCU3_ACTUALGEAR_R = 1;
    VCU3_ACTUALGEAR_N = 2;
    VCU3_ACTUALGEAR_1 = 3;
    VCU3_ACTUALGEAR_2 = 4;
    VCU3_ACTUALGEAR_3 = 5;
    VCU3_ACTUALGEAR_4 = 6;
    VCU3_ACTUALGEAR_5 = 7;
    VCU3_ACTUALGEAR_6 = 8;
    VCU3_ACTUALGEAR_7 = 9;
    VCU3_ACTUALGEAR_8 = 10;
    VCU3_ACTUALGEAR_RESERVED = 11;
    VCU3_ACTUALGEAR_NO_CONNECTION = 12;
    VCU3_ACTUALGEAR_INVALID_VALUE = 13;
  }
  // [mV] [0|2000]
  optional int32 vcu3_throttlevoltage = 1;
  // The signal indicates if the  ON/OFF cruise control switch is actived or not. [] [0|1]
  optional Vcu3_mainswitchType vcu3_mainswitch = 2;
  // The signal indicates if the increase speed switch is actived or not [] [0|1]
  optional Vcu3_increasespeedswitchType vcu3_increasespeedswitch = 3;
  // The signal indicates if  increase distance switch is actived or not [] [0|1]
  optional Vcu3_increasedistanceswitchType vcu3_increasedistanceswitch = 4;
  // The signal indicates if the decrease speed switch is actived or not. [] [0|1]
  optional Vcu3_decreasespeedswitchType vcu3_decreasespeedswitch = 5;
  // The signal indicates if decrease distance switch is actived or not [] [0|1]
  optional Vcu3_decreasedistanceswitchType vcu3_decreasedistanceswitch = 6;
  // The signal indicates if the cancel cruise control switch is actived or not [] [0|1]
  optional Vcu3_cancelswitchType vcu3_cancelswitch = 7;
  // This signal indicate the security button in the knob is pressed or not. [] [0|1]
  optional Vcu3_gearsecuritybuttonType vcu3_gearsecuritybutton = 8;
  // This signal indicate the park button in the knob is pressed or not. [] [0|1]
  optional Vcu3_gearparkbuttonType vcu3_gearparkbutton = 9;
  // This signal indicate the current lever position. [] [0|7]
  optional Vcu3_gearleverpositionType vcu3_gearleverposition = 10;
  // This signal indicate the EPB switch status. [] [0|3]
  optional Vcu3_epbswitchType vcu3_epbswitch = 11;
  // [kPa] [-108|96.6]
  optional double vcu3_vacuumpressure = 12;
  // The Livecounter is used to check the signal consistency of the messages [count] [0|15]
  optional int32 vcu3_livecounter = 13;
  // This signal indicates the lever position information which should be displayed on the dashboard. For H72G, only P,R,N,D,M,no connection. [] [0|15]
  optional Vcu3_leverinfoType vcu3_leverinfo = 14;
  // The signal indicates the working status of EPB. [] [0|3]
  optional Vcu3_epbstatusType vcu3_epbstatus = 15;
  // The checksum is used to check whether the data transmission errors [check] [0|255]
  optional int32 vcu3_checksum = 16;
  // The signal indicates to the actual gear status, it shows in which gear the transmission system is in at the moment (engaged gear). [] [0|15]
  optional Vcu3_actualgearType vcu3_actualgear = 17;
}

message Epb1_2a1 {
// Report Message
  // The Livecounter is used to check the signal consistency of the messages [] [0|0]
  optional int32 epb1_livecounter = 1;
  // 0:no request 1: lock 2 :release 3: reserved [] [0|0]
  optional int32 epb1_epbswitch = 2;
  // 0: released 1: locked 2: releasing 3:locking [] [0|0]
  optional int32 epb1_epbstatus = 3;
  // [] [0|0]
  optional int32 epb1_checksum = 4;
}

message Jt {
  optional Acu1_151 acu1_151 = 1; // control message
  optional Acu2_152 acu2_152 = 2; // control message
  optional Acu3_153 acu3_153 = 3; // control message
  optional Acu4_154 acu4_154 = 4; // control message
  optional Acs1_20c acs1_20c = 5; // report message
  optional Acs2_20d acs2_20d = 6; // report message
  optional Acs3_20e acs3_20e = 7; // report message
  optional Vcu1_210 vcu1_210 = 8; // report message
  optional Vcu2_211 vcu2_211 = 9; // report message
  optional Vcu3_212 vcu3_212 = 10; // report message
  optional Epb1_2a1 epb1_2a1 = 11; // report message
}
