load("//tools/install:install.bzl", "install", "install_src_files")

package(default_visibility = ["//visibility:public"])

install(
    name = "install",
    deps = [
 
    ],
)

install_src_files(
    name = "install_src",
    deps = [

    ],
)
